ZooWeb/Controllers/AddNewAnimalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZooWeb.Models;
using System.Text.RegularExpressions;

namespace ZooWeb.Controllers
{
    public class AddNewAnimalController : Controller
    {
        ZooEntities storeDB = new ZooEntities();

        public ActionResult Index()
        {
            List<string> list = new List<string>();
            list = DB_Manager_Animal.GetSpeciesNameList(storeDB);

            return View(list);
        }

        public ActionResult FillAnimalData(string speciesname)
        {            
            Animal animal = new Animal("GiveAName", speciesname);

            return View(animal);
        }


        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult DispAnimalDataSelectField()
        {
            string speciesName = Request.Form["SpeciesName000"];
            string firstName = Request.Form["FirstName000"];

            Animal animal = new Animal(firstName, speciesName); //for listbox only

            List<string> list = new List<string>();

            list = Logic.CreateListOfFieldsIdStringsToPlace(animal, storeDB);
             
            List<SelectListItem> selList = new List<SelectListItem>();

            //selList.Add(new SelectListItem { Text = "Week 1", Value = "Week1" });            
            int i = 0;
            foreach (string item in list)
	        {
                selList.Add(new SelectListItem { Text = list.ElementAt(i), Value = list.ElementAt(i) });
                i++;
	        }
            
            ViewBag.List = selList;
            ViewBag.Animal = animal;
            return View();       
        }

        [HttpPost]
        public ActionResult SaveAnimal(string SelId)
        {
            string speciesName = Request.Form["SpeciesName000"];
            string firstName = Request.Form["FirstName000"];

            Animal animal = new Animal(firstName, speciesName); //for listbox only
            
            ViewBag.Selstr = SelId;
            ViewBag.CreateFieldMsg = "";
            

            if(SelId==null)
            {
                ViewBag.CreateFieldMsg = "Pleasse create a place for the animal.";
            }
            else
            {

                string newString = Regex.Replace(SelId, "[^.0-9]", "");
                int num = int.Parse(newString);
                animal.SetLivingFieldNb(num);
                storeDB.Animals.Add(animal);


                Field field = DB_Manager_Field.GetAField(num, storeDB);
                field.AnimalsInOnePlace.Add(animal);

                storeDB.SaveChanges();
            }
            
            
            //return View(); 
            return RedirectToAction("Index");

        }        
        
    }
}

ZooWeb/Views/AddNewAnimal/Delete.cshtml
@model ZooWeb.Animal

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Animal</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SpeciesName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SpeciesName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IsCarnivorous)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IsCarnivorous)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.BirthDay)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BirthDay)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FirstName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FirstName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LivingFieldType)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LivingFieldType)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LivingFieldNb)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LivingFieldNb)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

ZooWeb/Views/AddNewAnimal/Details.cshtml
@model ZooWeb.Animal

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Animal</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SpeciesName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SpeciesName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IsCarnivorous)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IsCarnivorous)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.BirthDay)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BirthDay)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FirstName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FirstName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LivingFieldType)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LivingFieldType)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LivingFieldNb)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LivingFieldNb)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.AnimalId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ZooWeb/Views/AddNewAnimal/DispAnimalDataSelectField.cshtml
@{
    ViewBag.Title = "DispAnimalDataSelectField";
}

<h2>DispAnimalDataSelectField</h2>

@using (Html.BeginForm("SaveAnimal", "AddNewAnimal"))
{ 
<body>
    <div>
        species name:- <input type="text" value="@ViewBag.Animal.FirstName" name="FirstName000" readonly /> <br />
        species name:- <input type="text" value="@ViewBag.Animal.SpeciesName" name="SpeciesName000" readonly /> <br />
        speciesname = @ViewBag.Animal.SpeciesName;
        <br />
        first name = @ViewBag.Animal.FirstName;
        <br />
        @Html.DropDownList("SelId", (List<SelectListItem>)ViewBag.List)
        <br />
        <input type="submit" value="Create" />

    </div>
</body>
}

ZooWeb/Views/AddNewAnimal/Edit.cshtml
@model ZooWeb.Animal

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Animal</legend>

        @Html.HiddenFor(model => model.AnimalId)

        <div class="editor-label">
            @Html.LabelFor(model => model.SpeciesName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SpeciesName)
            @Html.ValidationMessageFor(model => model.SpeciesName)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ZooWeb/Views/AddNewAnimal/FillAnimalData.cshtml
@model ZooWeb.Animal
<body>
    <div>
        <form action="DispAnimalDataSelectField" method="post">
            <br />
            @Model.SpeciesName
            first name: <input type="text" name="FirstName000" /> <br />
            <input type="text" value="@Model.SpeciesName" name="SpeciesName000" hidden readonly /> <br />
            <input type="submit" value="OK and Select Place" />
        </form>


    </div>
</body>

ZooWeb/Views/AddNewAnimal/Index.cshtml
@model List<string>
@{
    ViewBag.Title = "Index";
}

<h2>Index Add new animal</h2>
<p>
    Select from @Model.Count() species:
</p>
<ul>
    @foreach (var spName in Model)
    {
        <li>
            @Html.ActionLink(spName, "FillAnimalData", new { speciesname = spName })
        </li>
    }

</ul>

ZooWeb/Views/AddNewAnimal/SaveAnimal.cshtml
@{
    ViewBag.Title = "SaveAnimal";
}

<h2>SaveAnimal</h2>

@ViewBag.SpeciesName
@ViewBag.SpeciesName
@ViewBag.FirstName
@ViewBag.Selstr
@Html.ActionLink("Back to main menu", "Index", "")